### PR TITLE
Polish some things in nod02a

### PR DESCRIPTION
**Pull request by abcdefg30**
- Made `CheckForBase` actually working
- Renamed some stuff and removed tables at places where they can be left out imho (you don't need to aply those changes to other missions.)

Just fetch and rebase again after accepting.
Feel free to leave comments if something is wrong/unclear.

### CODE REVIEW

**Comment by 42foobar42** [comment]
Hey,
I understand your changes and I am sure it will work. 
But when I wrote this functions CheckForBase, checkProduction and  getStartUnits  I had in mind that this functions are needed in many missions. So I made them as flexbile as I could so that also they can be used for other missions and other players like gdi.
In my opinion it would be usefull if they were part of the lua api in openra.
So I am not sure if it is the best way to accept this changes....

**Comment by abcdefg30** [comment]
Imho, they don't need to be that flexible here in this mission.
You can still use the flexible version for other missions.

**Comment by abcdefg30** [comment]
It's up to you. A clear "No" and I'll revert those changes.

**Comment by obrakmann** [comment]
I think the mission is fine now as it is. Sure, the style is different from our existing missions, but that's what you expect from a new author.

I don't agree with the idea of adding lua functions to the API, though. We've had that in the previous (first) incarnation of the Lua API and it was a huge maintenance nightmare. We shouldn't make that mistake again. The Lua API should be C# only.

**Comment by 42foobar42** [comment]
Your right in this case I don't need to be this flexible. I will merge this changes.

But again the question: A function like checkBase is needed in many missions and maybe usefull for other people who make maps. So wouldn't it make sense to provide such a function for all, instead of implementing it over and over again in lua scripts of the maps? 
Just a proposal....

**Pull request merged**
